### ISSUE TITLE
Where is the ExperimentRegistery.kt ?

### ISSUE THREAD

**Issue by Str4ky** [JRoy/discord-experiments-android#1]
I wanted to add more experiments to my Discord but idk where the ExperimentRegistery.kt file is located (they said on the app that i need to edit this file to add new experiments)

**Comment by JRoy** [comment]
The file would be in `output/smali/com/discord/utilities/experiments/ExperimentRegistry.smali`. Out of curiosity, what experiment did you want to add as I may add a better way to register experiments?

**Comment by Str4ky** [comment]
"Friends nicknames", and maybe "1st DM Accept & Report" (or maybe as many as you can if they're compatible with Discord Android), and also, do you know why notifications don't disepear when i go on a channel with one ? (i have to click on the cross at the top of my screen to mark them as read)

**Comment by JRoy** [comment]
>  also, do you know why notifications don't disepear when i go on a channel with one ? (i have to click on the cross at the top of my screen to mark them as read)

This is a current discord bug, I assume they'll fix it when they get back in the office tomorrow

**Comment by JRoy** [comment]
I've registered the few hidden experiments there are in f5afc9572c845deaeaeb62f35237983414fd7480

I will add a way to better manually register them in the future.
