### ISSUE TITLE
Installation not possible [resolved]

### ISSUE THREAD

**Issue by Syhix** [JRoy/discord-experiments-android#2]
When I try to install the APK it tells me that app not installed. I have version 106200

**Comment by JRoy** [comment]
What phone and Android version are you using? Also can you share a adb logcat of you installing the app.

**Comment by Syhix** [comment]
Samsung J4+
Android 9
How to use the adb logcat?

**Comment by JRoy** [comment]
> Samsung J4+ Android 9 How to use the adb logcat?

[Setup ADB](https://www.xda-developers.com/install-adb-windows-macos-linux/), plug your phone in, then run `adb logcat`, attempt to install the app, then share the output from your console from when you started the install.

**Comment by Syhix** [comment]
Launched the command as soon as I installed it, hope this helps you :)
[logcat.txt](https://github.com/JRoy/discord-experiments-android/files/7684960/logcat.txt)

**Comment by Syhix** [comment]
Hello, did you find where the problem came from?

**Comment by Syhix** [comment]
Problem solved, I uninstalled the app and took the patch, and it worked.
