### ISSUE TITLE
Lasted Release is Beta?

### ISSUE THREAD

**Issue by Aqua-neko-ow** [JRoy/discord-experiments-android#3]
The most recent release is Beta just asking because the last to where Canary? “119.5 (119105) - Beta”

**Comment by JRoy** [comment]
> The most recent release is Beta just asking because the last to where Canary? “119.5 (119105) - Beta”

Either discord stop releasing Canary versions or someone stopped uploading them to [ApkMirror](https://www.apkmirror.com/apk/discord-inc/). If someone were to continue uploading the apks to apkmirror the bot will start using the canary versions again.
